export const EVENTS = [
  {
    slug: 'react-conf-2024',
    image: '/events/event1.png',
    title: 'React Conf 2024',
    location: 'San Francisco, CA',
    date: 'March 15, 2024',
    time: '9:00 AM - 6:00 PM',
    id: 1,
  },
  {
    slug: 'nextjs-summit',
    image: '/events/event2.png',
    title: 'Next.js Summit',
    location: 'Austin, TX',
    date: 'April 22, 2024',
    time: '10:00 AM - 5:00 PM',
    id: 2,
  },
  {
    slug: 'javascript-world',
    image: '/events/event3.png',
    title: 'JavaScript World Conference',
    location: 'New York, NY',
    date: 'May 8, 2024',
    time: '8:30 AM - 7:00 PM',
    id: 3,
  },
  {
    slug: 'ai-hackathon-2024',
    image: '/events/event4.png',
    title: 'AI Innovation Hackathon',
    location: 'Seattle, WA',
    date: 'June 14-16, 2024',
    time: '48 Hours',
    id: 4,
  },
  {
    slug: 'web3-developer-meetup',
    image: '/events/event5.png',
    title: 'Web3 Developer Meetup',
    location: 'Miami, FL',
    date: 'July 20, 2024',
    time: '6:00 PM - 9:00 PM',
    id: 5,
  },
  {
    slug: 'fullstack-conference',
    image: '/events/event6.png',
    title: 'Full Stack Conference',
    location: 'Denver, CO',
    date: 'August 12, 2024',
    time: '9:00 AM - 6:00 PM',
    id: 6,
  },
  {
    slug: 'devops-unleashed',
    image: '/events/event1.png',
    title: 'DevOps Unleashed',
    location: 'Chicago, IL',
    date: 'September 5, 2024',
    time: '8:00 AM - 5:30 PM',
    id: 7,
  },
  {
    slug: 'mobile-dev-summit',
    image: '/events/event2.png',
    title: 'Mobile Development Summit',
    location: 'Los Angeles, CA',
    date: 'October 18, 2024',
    time: '9:30 AM - 6:00 PM',
    id: 8,
  },
  {
    slug: 'cybersecurity-conference',
    image: '/events/event3.png',
    title: 'Cybersecurity Conference',
    location: 'Boston, MA',
    date: 'November 2, 2024',
    time: '8:00 AM - 7:00 PM',
    id: 9,
  },
  {
    slug: 'data-science-hackathon',
    image: '/events/event4.png',
    title: 'Data Science Hackathon',
    location: 'San Diego, CA',
    date: 'December 7-9, 2024',
    time: '72 Hours',
    id: 10,
  },
  {
    slug: 'cloud-native-meetup',
    image: '/events/event5.png',
    title: 'Cloud Native Meetup',
    location: 'Portland, OR',
    date: 'January 15, 2025',
    time: '6:30 PM - 9:00 PM',
    id: 11,
  },
  {
    slug: 'frontend-masters',
    image: '/events/event6.png',
    title: 'Frontend Masters Conference',
    location: 'Nashville, TN',
    date: 'February 28, 2025',
    time: '9:00 AM - 5:00 PM',
    id: 12,
  },
];
